In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc
from math import pi, sin, sqrt
from multiprocessing import Pool, cpu_count, Queue
%matplotlib inline

rc('text', usetex=True)

In [23]:
T, sep, c = 5, 1, 90


N = 1000 // sep
samples = np.linspace(0, 1, N)  # Enough for 1 period (assuming integer c).
freqs = np.array([c - (2*n + T-1)*sep/2 for n in range(T)])
print(freqs)

waves = np.outer(samples, freqs[1:T])
wave = np.sin(np.multiply(freqs[0], samples))  # The first wave has no relative phase.

def power(rolls):
    phase_set = np.random.random((rolls, N, T-1))
    waves = np.array([waves,]*rolls)
    form = np.add(wave, np.sin(np.add(waves, phase_set)).transpose().sum(axis=0))   # Un-Normalized sum of waves
    form = np.divide(form, form.max())                                           # Normalized for Max Peak

    buf = sqrt(form.dot(form) / len(form))**2  # Proportional to Power (Vrms^2)

[[1, 2], [3, 4]]
[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [51]:
core = np.array([[1, 2], [2, 4], [3, 6]])

num = 3
dat = np.array([core,]*num)

phi = np.random.random((num, 1, 2))

print(phi)
print(dat)
dat = np.add(dat, phi)
dat = np.transpose(dat, axes=(0, 2, 1)).sum(axis=1)

wav = np.array([1, 2, 3])
dat = np.add(wav, dat)

normed = np.divide(dat, np.expand_dims(dat.max(axis=1), axis=1))

print(normed)

for vec in normed:
    print(vec)
    print(vec.dot(vec))
    
normed.dot(normed)

[[[0.80403805 0.63022519]]

 [[0.56238397 0.09809561]]

 [[0.5947957  0.90110561]]]
[[[1 2]
  [2 4]
  [3 6]]

 [[1 2]
  [2 4]
  [3 6]]

 [[1 2]
  [2 4]
  [3 6]]]
[[0.40450772 0.70225386 1.        ]
 [0.3681124  0.6840562  1.        ]
 [0.40722744 0.70361372 1.        ]]
[0.40450772 0.70225386 1.        ]
1.656786984993553
[0.3681124 0.6840562 1.       ]
1.6034396299102935
[0.40722744 0.70361372 1.        ]
1.6609064514821879


array([[0.82936229, 1.46806194, 2.10676159],
       [0.80794132, 1.43005496, 2.05216861],
       [0.83096302, 1.47090209, 2.11084116]])

In [ ]:
N = 1000                  # Samples;  1MHz is periodic to 1000 samples, Fsamp = 1GHz
C = 3                     # Cycles
samples = np.linspace(0, C, C*1000)

ntraps = 5
spacings = 1              # MHz
center = 81               # Mhz

freqs = np.array([center - (2*n + ntraps-1)*spacing/2 for n in range(ntraps)])
###########################


def rat(waves, dat, phases):
    dat = np.add(dat, np.sin(np.add(waves, phases)).transpose().sum(axis=0))
    
    peak = dat.max()
    rms = sqrt(dat.dot(dat) / N)
    return rms / peak

def rat_plot(waves, dat, phases):
    return np.add(dat, np.sin(np.add(waves, phases)).transpose().sum(axis=0))


waves = np.outer(samples, freqs[1:ntraps], dtype=float)
dat = np.sin(np.multiply(freqs[0], samples))  # The first wave has no relative phase.
phases = np.random(ntraps-1)


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

for i in range(len(a.shape)):
    print(np.concatenate([a, b], axis=i))
    
msg = '{:%}%\n'.format(1 / len(a))
if msg is not None:
    print(msg)

    
a.dot(a)

In [ ]:
N = 5
sep = 1
c = 90
plot = True
params = (N, sep, c, rolls, plot)


find_optimal_fast(params)

In [ ]:
ATTEMPS = 10
N = 1000                  # Samples;  1MHz is periodic to 1000 samples, Fsamp = 1GHz
samples = np.linspace(0, 1, N)

ntraps = np.arange(15)
spacings = [1, 0.5]              # MHz
center = [80, 85, 90, 95, 100]   # Mhz

def optimize_phase_sets(ntraps, spacing, center, rolls=10):
    def params():
        for i, N in enumerate(ntraps):
            for j, sep in enumerate(spacings):
                for k, c in enumerate(center):
                    yield (N, sep, c)
                
    
    pool = Pool(processes=cpu_count())
    
    for pool.map(find_optimal, params)

###########################


    
        

def intensity(waves, form, phases):
    form = np.add(form, np.sin(np.add(waves, phases)).transpose().sum(axis=0))   # Un-Normalized sum of waves
    form = np.divide(form, form.max())                                           # Normalized for Max Peak
    
    return sqrt(form.dot(form) / len(form))**2  # Proportional to Power (Vrms^2)
        
def waveform(waves, dat, phases):
    dat = np.add(dat, np.sin(np.add(waves, phases)).transpose().sum(axis=0))
    return np.divide(dat, dat.max())
    
freqs = np.array([center - (2*n + ntraps-1)*spacing/2 for n in range(ntraps)])

waves = np.outer(samples, freqs[1:ntraps], dtype=float)
dat = np.sin(np.multiply(freqs[0], samples))  # The first wave has no relative phase.
phases = np.random(ntraps-1)


In [ ]:
np.full((2,2), 3)

In [ ]:
a = np.array([1, 2, 3])



In [ ]:
a = np.ones((2,2))
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

np.outer(b, a)

In [ ]:
import numpy as np

a = np.array([[9, 1, 8], [2, 7, 3], [6, 4, 5]])
b = np.array([3, 2, 1])

print(np.add(a, b))
print(np.add(a.transpose(), b))
print(np.add(b, a).sum(axis=0))
print(np.add(b, a.transpose()).sum(axis=0))


np.sin(a)

In [ ]:
phases = np.linspace(-2*pi, 2*pi, 100)
workers = Pool(processes=cpu_count())

results = []

for p1 in phases: 
    args = [(p1, p2) for p2 in phases]
    results.append(workers.map(rat, args))

In [ ]:
npi = np.linspace(-2, 2, 100)

plt.figure(figsize=(8,5))
plt.pcolor(npi, npi, results, cmap='Blues')
plt.title(r"$(A_{rms} / A_{max})$ for 80, 81, 82 MHz Superimposed", fontsize=24)
plt.xlabel("$\phi_1 / \pi$", fontsize=25)
plt.ylabel("$\phi_2 / \pi$", fontsize=25)
plt.xticks(fontsize=20)
plt.yticks(fontsize=20)

plt.subplots_adjust(top = 1.1, bottom = 0, right = 1, left = 0, 
            hspace = 0, wspace = 0)
plt.margins(0,0)

plt.savefig("phase_map.png", bbox_inches = 'tight',
    pad_inches = 0)

plt.show()